---
- name: Deploy vexination walker Pod
  ansible.builtin.include_tasks: install_manifest_cronjob.yml
  when: not tpa_single_node_vexination_walker_suspended
  vars:
    podman_spec:
      state: stopped
      systemd_file: vexination-walker
      timer_type: monotonic # realtime
      time_pattern: 1h # *:0/10 for realtime instead of monotonic
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/vexination/walker/Deployment.yaml.j2') | from_yaml }}"
