---
- name: Deploy init-dataset Pod
  ansible.builtin.include_tasks: install_manifest.yml
  vars:
    podman_spec:
      state: stopped
      systemd_file: init-dataset
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/init/dataset/Deployment.yaml.j2') | from_yaml }}"
      configmaps:
        - "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/custom-trust-anchor.yaml"
