---
- name: Configure and deploy Postgres
  ansible.builtin.include_tasks: infra/postgresql.yml
  args:
    apply:
      become: true

- name: Configure OIDC
  ansible.builtin.include_tasks: infra/oidc.yml

- name: Configure Storage
  ansible.builtin.include_tasks: infra/storage.yml

- name: Configure Events
  ansible.builtin.include_tasks: infra/events.yml

- name: Configure Trust Anchor
  ansible.builtin.include_tasks: infra/trust_anchor.yml
