---
- name: Confirmed required parameters provided
  ansible.builtin.assert:
    that:
      - tpa_single_node_base_hostname is defined
      - tpa_single_node_base_hostname | trim | length > 0
    msg: "'tpa_single_node_base_hostname' must be specified"

- name: Get RHTPA network details
  containers.podman.podman_network:
    name: "{{ tpa_single_node_podman_network }}"
  register: tpa_podman_network_results

- name: Set DNS Resolver
  ansible.builtin.set_fact:
    dns_resolver: "{{ tpa_podman_network_results.network.subnets[0].gateway }}"

- name: Copy init-db.sql to Server
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.template', 'configs/init-db.sql') }}"
    dest: "/tmp/init-db.sql"
    remote_src: true
    mode: "0666"

- name: Run init-db.sql
  ansible.builtin.command:
    cmd: >
      psql -v ON_ERROR_STOP=1
      -v db_name={{ tpa_single_node_pg_db }}
      -v db_user={{ tpa_single_node_pg_user }}
      -v db_password={{ tpa_single_node_pg_user_passwd }}
      -f /tmp/init-db.sql
  changed_when: false
  become: true
  become_user: postgres

- name: Create psql test command template
  ansible.builtin.template:
    src: "templates/scripts/psql_test.sh.j2"
    dest: "/tmp/psql_test.sh"
    mode: "0755"

- name: Testing DB guac to make sure it is available
  ansible.builtin.shell: "/tmp/psql_test.sh"
