---
- name: Generate bombastic-api secret manifest
  ansible.builtin.template:
    src: "{{ role_path }}/templates/manifests/bombastic/api/Secret.yaml.j2"
    dest: "{{ tpa_single_node_kube_manifest_dir }}/Secrets/bombastic-api.yaml"
    mode: "0600"
  vars:
    tpa_single_node_bombastic_api_tls_cert_pem: "{{ lookup('file', tpa_single_node_bombastic_api_tls_crt_path) }}"
    tpa_single_node_bombastic_api_tls_cert_key: "{{ lookup('file', tpa_single_node_bombastic_api_tls_key_path) }}"

- name: Play bombastic-api secret manifest
  ansible.builtin.command:
    cmd: "podman kube play {{ tpa_single_node_kube_manifest_dir }}/Secrets/bombastic-api.yaml"
  changed_when: true

- name: Create configmap auth for bombastic-api
  ansible.builtin.include_tasks: infra/component_auth.yml
  vars:
    component:
      name: "bombastic"
      type: "api"

- name: Deploy bombastic-api
  ansible.builtin.include_tasks: install_manifest.yml
  vars:
    podman_spec:
      state: started
      systemd_file: bombastic-api
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/bombastic/api/Deployment.yaml.j2') | from_yaml }}"
      configmaps:
        - "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/bombastic-api.yaml"
      configmap_changed: oidc_configmap_result.changed
