---
- name: Create configmap auth for bombastic-api
  ansible.builtin.include_tasks: infra/component_auth.yml
  vars:
    component:
      name: "bombastic"
      type: "api"

- name: Deploy bombastic-api
  ansible.builtin.include_tasks: install_manifest.yml
  vars:
    podman_spec:
      state: started
      systemd_file: bombastic-api
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/bombastic/api/Deployment.yaml.j2') | from_yaml }}"
      configmaps:
        - "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/bombastic-api.yaml"
        - "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/custom-trust-anchor.yaml"
      configmap_changed: oidc_configmap_result.changed
