apiVersion: apps/v1
kind: Deployment
metadata:
  name: guac-graphql
  namespace: trustification
  labels:
    app.kubernetes.io/name: guac-graphql
    app.kubernetes.io/component: guac
    app.kubernetes.io/instance: redhat-trusted-profile-analyzer
    app.kubernetes.io/version: 1.1.1
    app.kubernetes.io/part-of: trusted-profile-analyzer
  annotations: null
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: guac-graphql
      app.kubernetes.io/component: guac
      app.kubernetes.io/instance: redhat-trusted-profile-analyzer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guac-graphql
        app.kubernetes.io/component: guac
        app.kubernetes.io/instance: redhat-trusted-profile-analyzer
    spec:
      initContainers:
        - name: migrate
          image: {{ tpa_single_node_guac_image }}
          imagePullPolicy: IfNotPresent
          command:
            - /opt/guac/guacmigrate
          args:
            - --db-address=postgres://{{ tpa_single_node_pg_user }}:{{ tpa_single_node_pg_user_passwd }}@{{ tpa_single_node_pg_host }}:{{ tpa_single_node_pg_port }}/{{ tpa_single_node_pg_db }}?sslmode={{ tpa_single_node_pg_ssl_mode }}
            - --db-driver=postgres
            - --db-debug=true
          workingDir: /opt/guac
          volumeMounts: null
      containers:
        - name: service
          image: {{ tpa_single_node_guac_image }}
          imagePullPolicy: IfNotPresent
          tty: true     
          stdin: true   
          command:
            - /opt/guac/guacgql 
          args:
            - --gql-listen-port=8080
            - --gql-backend=ent
            - --db-address=postgres://{{ tpa_single_node_pg_user }}:{{ tpa_single_node_pg_user_passwd }}@{{ tpa_single_node_pg_host }}:{{ tpa_single_node_pg_port }}/{{ tpa_single_node_pg_db }}?sslmode={{ tpa_single_node_pg_ssl_mode }}
            - --db-driver=postgres
            - --db-debug=true
            - --gql-debug=true
          workingDir: /opt/guac
          env:
            - name: GUAC_PROMETHEUS_ADDR
              value: '9010'
          volumeMounts:
            - mountPath: /etc/tls
              name: tls
              readOnly: true
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTPS
          ports:
            - containerPort: 9010
              protocol: TCP
              name: infra
            - containerPort: 8080
              protocol: TCP
              name: endpoint
      volumes:
        - name: tls
          secret:
            secretName: guac-graphql-tls
