---
- name: Deploy guac-collectsub Pod
  ansible.builtin.include_tasks: install_manifest.yml
  vars:
    podman_spec:
      state: started
      systemd_file: guac-collectsub
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/guac/collectsub/Deployment.yaml.j2') | from_yaml }}"
