---
- name: Copy init-db.sql to Server
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.template', 'configs/init-db.sql') }}"
    dest: "/tmp/init-db.sql"
    remote_src: true
    mode: "0666"

- name: Run init-db.sql
  ansible.builtin.command:
    cmd: >
      psql -v ON_ERROR_STOP=1
      -v db_name={{ tpa_single_node_pg_db }}
      -v db_user={{ tpa_single_node_pg_user }}
      -v db_password={{ tpa_single_node_pg_user_passwd }}
      -f /tmp/init-db.sql
  changed_when: false
  become: true
  become_user: postgres

- name: Testing DB guac to make sure it is available
  ansible.builtin.command: "psql postgresql://{{ tpa_single_node_pg_user }}:{{ tpa_single_node_pg_user_passwd }}@\
  {{ tpa_single_node_pg_host }}:{{ tpa_single_node_pg_port }}/{{ tpa_single_node_pg_db }} -c 'SELECT 1'"
  register: select_output
  changed_when: false
