---
# Init Guac DBMS
- name: Configure and initialize Guac DBMS
  ansible.builtin.include_tasks: guac/init.yml

- name: Provision Guac collectsub
  ansible.builtin.include_tasks: guac/guac_collectsub.yml
  vars:
    tpa_single_node_guac_csub_tls_cert_pem: "{{ lookup('file', tpa_single_node_guac_csub_tls_crt_path) }}"
    tpa_single_node_guac_csub_tls_cert_key: "{{ lookup('file', tpa_single_node_guac_csub_tls_key_path) }}"

- name: Provision Guac graphql
  ansible.builtin.include_tasks: guac/guac_graphql.yml
  vars:
    tpa_single_node_guac_graphql_tls_cert_pem: "{{ lookup('file', tpa_single_node_guac_graphql_tls_crt_path) }}"
    tpa_single_node_guac_graphql_tls_cert_key: "{{ lookup('file', tpa_single_node_guac_graphql_tls_key_path) }}"
