---
# vars file for tpa_scaffolding
tpa_single_node_base_hostname: trustification
tpa_single_node_rhel_host: "{{ lookup('env', 'TPA_RHEL_HOST') | default('192.168.121.60', true) }}"
tpa_single_node_certificates_dir: certs/
tpa_single_node_config_dir: /etc/rhtpa
tpa_single_node_kube_manifest_dir: "{{ tpa_single_node_config_dir }}/manifests"
tpa_single_node_namespace: trustification
tpa_single_node_podman_network: tcnet
tpa_single_node_skip_os_install: true
tpa_single_node_systemd_directory: /etc/systemd/system
tpa_single_node_default_empty: ""

# DB_SERVICE
tpa_single_node_pg_host: "{{ lookup('env', 'TPA_PG_HOST') | default('192.168.121.60', true) }}"
tpa_single_node_pg_port: 5432
tpa_single_node_pg_db: guac
tpa_single_node_pg_user: guac
tpa_single_node_pg_user_passwd: guac1234
tpa_single_node_pg_ssl_mode: disable

# Storage Service
tpa_single_node_storage_type: s3 # Either s3 or minio
tpa_single_node_storage_access_key: "{{ lookup('env', 'TPA_STORAGE_ACCESS_KEY') }}"
tpa_single_node_storage_secret_key: "{{ lookup('env', 'TPA_STORAGE_SECRET_KEY') }}"
tpa_single_node_storage_bombastic_bucket: bombastic-rhtpa # <bombastic storage bucket name>
tpa_single_node_storage_v11y_bucket: v11y-rhtpa # <v11y storage bucket name>
tpa_single_node_storage_vexination_bucket: vexination-rhtpa # <v11y storage bucket name>
tpa_single_node_storage_region: eu-west-1 # <AWS S3 Storage region> # For Minio just keep eu-west-1

## Storage Service - Minio fields
tpa_single_node_storage_endpoint: # <Enter minio storage endpoint, For AWS this field is not necessary>

# SQS_SERVICE
tpa_single_node_event_bus_type: sqs # Either kafka or sqs
tpa_single_node_event_access_key_id: "{{ lookup('env', 'TPA_EVENT_ACCESS_KEY_ID') }}" # Kafka Username or AWS SQS Access Key ID
tpa_single_node_event_secret_access_key: "{{ lookup('env', 'TPA_EVENT_SECRET_ACCESS_KEY') }}" # Kafka password or AWS SQS Secret Access Key
tpa_single_node_bombastic_topic_failed: bombastic-failed-rhtpa # Bombastic Events topic failed
tpa_single_node_bombastic_topic_indexed: bombastic-indexed-rhtpa # Bombastic Events topic indexed
tpa_single_node_bombastic_topic_stored: bombastic-stored-rhtpa # Bombastic Events topic stored
tpa_single_node_vexination_topic_failed: vexination-failed-rhtpa # Vexination Events topic failed
tpa_single_node_vexination_topic_indexed: vexination-indexed-rhtpa # Vexination Events topic indexed
tpa_single_node_vexination_topic_stored: vexination-stored-rhtpa # Vexination Events topic stored
tpa_single_node_v11y_topic_failed: v11y-failed-rhtpa # v11y Events topic failed
tpa_single_node_v11y_topic_indexed: v11y-indexed-rhtpa # v11y Events topic indexed
tpa_single_node_v11y_topic_stored: v11y-stored-rhtpa # v11y Events topic stored

### Kafka fields
# <Only needed for Kafka service, For AWS this field is not necessary>
tpa_single_node_kafka_bootstrap_servers: "{{ lookup('env', 'TPA_EVENT_BOOTSTRAP_SERVER') | default('tpa_single_node_default_empty', true) }}"
# Security protocol used for Kafka user authentication.
tpa_single_node_kafka_security_protocol: # Example - SASL_PLAINTEXT
# Kafka Authentication Mechanism which is spec.kafka.listeners.authentication.type in Block letters.
tpa_single_node_kafka_auth_mechanism: # Example - SCRAM-SHA-512

### AWS SQS fields
tpa_single_node_sqs_region: eu-west-1 # AWS SQS Region

# SSO_SERVICE
tpa_single_node_oidc_type: cognito # Either cognito or keycloak
tpa_single_node_oidc_issuer_url: "{{ lookup('env', 'TPA_OIDC_ISSUER_URL') | default('tpa_single_node_default_empty', true) }}"
tpa_single_node_oidc_frontend_id: "{{ lookup('env', 'TPA_OIDC_FRONTEND_ID') | default('tpa_single_node_default_empty', true) }}"
tpa_single_node_oidc_provider_client_id: "{{ lookup('env', 'TPA_OIDC_PROVIDER_CLIENT_ID') | default('tpa_single_node_default_empty', true) }}"
tpa_single_node_oidc_provider_client_secret: "{{ lookup('env', 'TPA_OIDC_PROVIDER_CLIENT_SECRET') | default('tpa_single_node_default_empty', true) }}"

## AWS OIDC fields
tpa_single_node_aws_cognito_domain: "{{ lookup('env', 'TPA_OIDC_COGNITO_DOMAIN') | default('tpa_single_node_default_empty', true) }}"

# TSL Certificates
tpa_single_node_guac_csub_tls_cert_pem_path: "{{ tpa_single_node_certificates_dir }}/guac-collectsub-tls-certificate.pem"
tpa_single_node_guac_csub_tls_cert_key_path: "{{ tpa_single_node_certificates_dir }}/guac-collectsub-tls-certificate.key"
tpa_single_node_guac_graphql_tls_cert_pem_path: "{{ tpa_single_node_certificates_dir }}/guac-graphql-tls-certificate.pem"
tpa_single_node_guac_graphql_tls_cert_key_path: "{{ tpa_single_node_certificates_dir }}/guac-graphql-tls-certificate.key"
tpa_single_node_collector_osv_tls_cert_pem_path: "{{ tpa_single_node_certificates_dir }}/collector-osv-tls-certificate.pem"
tpa_single_node_collector_osv_tls_cert_key_path: "{{ tpa_single_node_certificates_dir }}/collector-osv-tls-certificate.key"
tpa_single_node_collector_osv_tls_client_cert_crt_path: "{{ tpa_single_node_certificates_dir }}/collector-osv-tls-client-certificate.crt"
tpa_single_node_collectorist_api_tls_cert_pem_path: "{{ tpa_single_node_certificates_dir }}/collectorist-api-tls-certificate.pem"
tpa_single_node_collectorist_api_tls_cert_key_path: "{{ tpa_single_node_certificates_dir }}/collectorist-api-tls-certificate.key"
tpa_single_node_collectorist_api_tls_csub_cert_crt_path: "{{ tpa_single_node_certificates_dir }}/collectorist-api-tls-csub-certificate.crt"
tpa_single_node_spog_api_tls_cert_pem_path: "{{ tpa_single_node_certificates_dir }}/spog-api-tls-certificate.pem"
tpa_single_node_spog_api_tls_cert_key_path: "{{ tpa_single_node_certificates_dir }}/spog-api-tls-certificate.key"
tpa_single_node_spog_ui_tls_cert_pem_path: "{{ tpa_single_node_certificates_dir }}/spog-ui-tls-certificate.pem"
tpa_single_node_spog_ui_tls_cert_key_path: "{{ tpa_single_node_certificates_dir }}/spog-ui-tls-certificate.key"

# Target node(s) - Secret and Configmap locations
tpa_single_node_storage_secret: "{{ tpa_single_node_kube_manifest_dir }}/storage-secret.yaml"
tpa_single_node_event_secret: "{{ tpa_single_node_kube_manifest_dir }}/event-secret.yaml"
tpa_single_node_oidc_secret: "{{ tpa_single_node_kube_manifest_dir }}/oidc-secret.yaml"

# ports
tpa_single_node_spog_ui_port: 8080
tpa_single_node_vexination_api_port: 8081
tpa_single_node_bombastic_api_port: 8082
tpa_single_node_spog_api_port: 8084
tpa_single_node_v11y_api_port: 8087

# Services suspended
tpa_single_node_bombastic_walker_suspended: true
tpa_single_node_datasset_job_suspended: true
tpa_single_node_vexination_walker_suspended: true
tpa_single_node_v11y_walker_suspended: false
